services:
  - type: web
    name: wrecksshop-bot
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars: 
      - key: DISCORD_TOKEN
        sync: false
      - key: LOG_LEVEL
        value: INFO
