name: Build WrecksShop Windows EXE

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'data/**'
      - '.github/workflows/build-windows.yml'
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow==9.5.0 discord.py==2.3.2 pandas==2.1.2 python-dotenv==1.0.0 pyinstaller==5.8.0 ipaddress
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        shell: bash
        run: |
          pyinstaller --noconfirm --clean \
            --onedir \
            --windowed \
            --name WrecksShop \
            --add-data "data/CleanArkData.csv;data" \
            --icon logo.ico \
            --hidden-import=ipaddress \
            --hidden-import=pyimod02_importers \
            --collect-all PyInstaller \
            wrecksshop_launcher_gui.py


      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: WrecksShopLauncher
          path: dist/wrecksshop
