name: Build WrecksShop Windows EXE

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'data/**'
      - '.github/workflows/build-windows.yml'
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # PyInstaller (if not in requirements)
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        shell: bash
        run: |
          pyinstaller --noconfirm --clean \
            --name WrecksShop \
            --add-data "data/CleanArkData.csv;data" \
            --icon logo_icon.ico \
            arkshopbot_launcher.py


      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: WrecksShopLauncher
          path: dist/WrecksShop/
